sudo: false
language: node_js
node_js:
  - '6.6.0'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  # - npm run lint
  # - npm run test-once
  - npm run e2e
